name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        APPLICATION_NAME: "view_embeddings"
        ENVIRONMENT_NAME: "view-embeddings-dev"
      run: |
        zip -r application.zip .
        aws elasticbeanstalk create-application-version \
          --application-name $APPLICATION_NAME \
          --version-label $GITHUB_SHA \
          --source-bundle S3Bucket="your-s3-bucket-name",S3Key=application.zip
        aws elasticbeanstalk update-environment \
          --application-name $APPLICATION_NAME \
          --environment-name $ENVIRONMENT_NAME \
          --version-label $GITHUB_SHA
